- trying to make check nicer;

diff --git a/.github/workflows/build-and-upload.yml b/.github/workflows/build-and-upload.yml
--- a/.github/workflows/build-and-upload.yml
+++ b/.github/workflows/build-and-upload.yml
@@ -31,7 +31,7 @@ jobs:
     strategy:
       matrix:
         python_version: ['3.7', '3.8', '3.9', '3.10']
- #       os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
+#        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
         os: ['macos-latest']
         include:
 #          - os: ubuntu-latest
@@ -100,7 +100,16 @@ jobs:
 
       - name: Check that all required platforms are included
         if: matrix.os == 'macos-latest'
-        run: for P in x86_64 arm64 arm64e; do for F in build/lib.*/scalene/*.so ; do file $F | grep -q "\\b$P\\b" || exit 1; done; done
+        run: |
+          for P in x86_64 arm64 arm64e;
+            do for F in build/lib.*/scalene/*.so ; do
+              file $F | grep -q "\\b$P\\b"
+              if [ $? != 0 ]; then
+                echo "$P missing"
+                exit 1
+              fi
+            done
+          done
   
       - name: Non-release (dev) upload
         if: github.event_name != 'release'
